In [ ]:
#assignment
#with function and wihtout function do the matrix transpose
matrix=[[1,2,3,4],[6,7,3,4],[7,8,9,3]]
transpose=[]
for i in range(len(matrix[0])):
    row=[]
    for j in range(len(matrix)):
        row.append(matrix[j][i])
    transpose.append(row)
print(transpose)

[[1, 6, 7], [2, 7, 8], [3, 3, 9], [4, 4, 3]]


In [ ]:
import numpy as np
matrix=[[1,2,3,4],[6,7,3,4],[7,8,9,3]]
tran=np.transpose(matrix)
print(tran)

[[1 6 7]
 [2 7 8]
 [3 3 9]
 [4 4 3]]


In [ ]:
#assignment
#how to resign the data which temporaryily deleted using pop up
lst={1,2,3,4,5,6}
a=lst.pop()
b=lst.pop()
print(a)
print(b)
print(lst)
lst.add(a)
lst.add(b)
print(lst)

1
2
{3, 4, 5, 6}
{1, 3, 4, 5, 6, 2}


In [ ]:
#useing copy to copy a list
a=[1,2,3]
b=[]
b=a.copy()
print(id(a))
print(id(b))
print(b)

132968638853504
132968638849984
[1, 2, 3]
